// <auto-generated />
using Formacion.Data.Context.Resources;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Formacion.Data.Migrations.Resources
{
    [DbContext(typeof(ResourcesContext))]
    [Migration("20211210174831_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Formacion.Data.Models.Resources.ResourceCulture", b =>
                {
                    b.Property<int>("ResourceCultureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceCultureId"), 1L, 1);

                    b.Property<string>("CultureName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ResourceCultureId");

                    b.ToTable("ResourceCultures", (string)null);

                    b.HasData(
                        new
                        {
                            ResourceCultureId = 1,
                            CultureName = "en-GB"
                        },
                        new
                        {
                            ResourceCultureId = 2,
                            CultureName = "en-US"
                        });
                });

            modelBuilder.Entity("Formacion.Data.Models.Resources.TextResource", b =>
                {
                    b.Property<int>("TextResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TextResourceId"), 1L, 1);

                    b.Property<string>("TextIndex")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TextValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TextResourceId");

                    b.ToTable("TextResources", (string)null);

                    b.HasData(
                        new
                        {
                            TextResourceId = 1,
                            TextIndex = "ConfigMustHasValue",
                            TextValue = "Configuración debe tener un valor"
                        },
                        new
                        {
                            TextResourceId = 2,
                            TextIndex = "CurrentDateInvalid",
                            TextValue = "La fecha actual es incorrecta"
                        },
                        new
                        {
                            TextResourceId = 3,
                            TextIndex = "DateTimeMustHasValue",
                            TextValue = "La fecha debe tener un valor"
                        },
                        new
                        {
                            TextResourceId = 4,
                            TextIndex = "EndAtMinorStartingAt",
                            TextValue = "'Finaliza en' debe ser mas grande que 'Comienza en'"
                        },
                        new
                        {
                            TextResourceId = 5,
                            TextIndex = "EndAtNotHasValue",
                            TextValue = "'Finaliza en' debe tener un valor"
                        },
                        new
                        {
                            TextResourceId = 6,
                            TextIndex = "EndDateAerlierCurrentDate",
                            TextValue = "La fecha final no puede ser menor que la fecha actual"
                        },
                        new
                        {
                            TextResourceId = 7,
                            TextIndex = "EndDateGreatStartDate",
                            TextValue = "Fecha de finalización debe ser mayor que la fecha de comienzo"
                        },
                        new
                        {
                            TextResourceId = 8,
                            TextIndex = "EveryMustGreatZero",
                            TextValue = "Configuración semanal: 'Cada' debe ser mayor que zero"
                        },
                        new
                        {
                            TextResourceId = 9,
                            TextIndex = "MonthBeBetween1And12",
                            TextValue = "Configuracion mensual: mes(s) debe estar entre 1 y 12"
                        },
                        new
                        {
                            TextResourceId = 10,
                            TextIndex = "MustIndicateDayGreatZero",
                            TextValue = "Configuracion mensual: debe indicar un día del mes mayor que cero"
                        },
                        new
                        {
                            TextResourceId = 11,
                            TextIndex = "MustIndicateDayLes31",
                            TextValue = "Configuracion mensual: debe indicar un día del mes menor o igual que 31"
                        },
                        new
                        {
                            TextResourceId = 12,
                            TextIndex = "MustIndicateDayOfMonth",
                            TextValue = "Configuracion mensual: debe indicar un día del mes"
                        },
                        new
                        {
                            TextResourceId = 13,
                            TextIndex = "MustIndicateTypeEveryDay",
                            TextValue = "Configuracion mensual: debe indicar el tipo de cada día"
                        },
                        new
                        {
                            TextResourceId = 14,
                            TextIndex = "MustIndicateTypeOfDayWeek",
                            TextValue = "Configuracion mensual: debe indicar el tipo de día de la semana"
                        },
                        new
                        {
                            TextResourceId = 15,
                            TextIndex = "MustSelectDayWeek",
                            TextValue = "Configuración semanal: debe seleccionar un o mas días de la semana"
                        },
                        new
                        {
                            TextResourceId = 16,
                            TextIndex = "NotCalculate",
                            TextValue = "No hay calculo"
                        },
                        new
                        {
                            TextResourceId = 17,
                            TextIndex = "NotNextExecution",
                            TextValue = "No hay proxima ejecución"
                        },
                        new
                        {
                            TextResourceId = 18,
                            TextIndex = "NumberMustGreaZero",
                            TextValue = "Número de repeticiones debe ser mayor que cero"
                        },
                        new
                        {
                            TextResourceId = 19,
                            TextIndex = "OccursGreatZero",
                            TextValue = "'Ocurre cada' debe ser mayo o igual que cero"
                        },
                        new
                        {
                            TextResourceId = 20,
                            TextIndex = "OnceAtValue",
                            TextValue = "'Ocurre en' debe tener un valor"
                        },
                        new
                        {
                            TextResourceId = 21,
                            TextIndex = "StartDateInvalid",
                            TextValue = "Fecha de comienzo incorrecta"
                        },
                        new
                        {
                            TextResourceId = 22,
                            TextIndex = "StartingAtNotHasValue",
                            TextValue = "'Comienza en' debe tener un valor"
                        },
                        new
                        {
                            TextResourceId = 23,
                            TextIndex = "WrongConfiguration",
                            TextValue = "Configuración incorrecta"
                        },
                        new
                        {
                            TextResourceId = 24,
                            TextIndex = "FormatterDailyFrecuency_TextEvery",
                            TextValue = "cada {0} {1} entre las {2} y las {3}"
                        },
                        new
                        {
                            TextResourceId = 25,
                            TextIndex = "FormatterDailyFrecuency_TextOnce",
                            TextValue = "Ocurre una vez en {0}"
                        },
                        new
                        {
                            TextResourceId = 26,
                            TextIndex = "FormatterMonthly_TextBase",
                            TextValue = "Ocurre {0} cada {1} meses"
                        },
                        new
                        {
                            TextResourceId = 27,
                            TextIndex = "FormatterMonthly_TextTypeDay",
                            TextValue = "el {0}"
                        },
                        new
                        {
                            TextResourceId = 28,
                            TextIndex = "FormatterMonthly_TextTypeEvery",
                            TextValue = "el {0} {1}"
                        },
                        new
                        {
                            TextResourceId = 29,
                            TextIndex = "FormatterOnce_TextBase",
                            TextValue = "Ocurre una vez. El horario se utilizará el {0} a las {1} comenzando el {2}"
                        },
                        new
                        {
                            TextResourceId = 30,
                            TextIndex = "FormatterRecurring_TextBase",
                            TextValue = "{0} empezando el {1}"
                        },
                        new
                        {
                            TextResourceId = 31,
                            TextIndex = "FormatterRecurring_TextNoConfigWeekly",
                            TextValue = "Ocurre cada {0}{1}{2}. El horario se utilizará el {3} a las {4}"
                        },
                        new
                        {
                            TextResourceId = 32,
                            TextIndex = "FormatterWeekly_TextAnd",
                            TextValue = " y"
                        },
                        new
                        {
                            TextResourceId = 33,
                            TextIndex = "FormatterWeekly_TextBase",
                            TextValue = "Ocurre cada {0} semanas en {1}"
                        },
                        new
                        {
                            TextResourceId = 34,
                            TextIndex = "friday",
                            TextValue = "viernes"
                        },
                        new
                        {
                            TextResourceId = 35,
                            TextIndex = "monday",
                            TextValue = "lunes"
                        },
                        new
                        {
                            TextResourceId = 36,
                            TextIndex = "saturday",
                            TextValue = "sabado"
                        },
                        new
                        {
                            TextResourceId = 37,
                            TextIndex = "sunday",
                            TextValue = "domingo"
                        },
                        new
                        {
                            TextResourceId = 38,
                            TextIndex = "thursday",
                            TextValue = "jueves"
                        },
                        new
                        {
                            TextResourceId = 39,
                            TextIndex = "tuesday",
                            TextValue = "martes"
                        },
                        new
                        {
                            TextResourceId = 40,
                            TextIndex = "TypesEveryDayMonthly_Weekday",
                            TextValue = "entre semana"
                        },
                        new
                        {
                            TextResourceId = 41,
                            TextIndex = "TypesEveryMonthly_First",
                            TextValue = "primer"
                        },
                        new
                        {
                            TextResourceId = 42,
                            TextIndex = "TypesEveryMonthly_Fourth",
                            TextValue = "cuarto"
                        },
                        new
                        {
                            TextResourceId = 43,
                            TextIndex = "TypesEveryMonthly_Last",
                            TextValue = "último"
                        },
                        new
                        {
                            TextResourceId = 44,
                            TextIndex = "TypesEveryMonthly_Second",
                            TextValue = "segundo"
                        },
                        new
                        {
                            TextResourceId = 45,
                            TextIndex = "TypesEveryMonthly_Third",
                            TextValue = "tercero"
                        },
                        new
                        {
                            TextResourceId = 46,
                            TextIndex = "TypesEveryDayMonthly_Weekend",
                            TextValue = "fin de semana"
                        },
                        new
                        {
                            TextResourceId = 47,
                            TextIndex = "TypesOccurs_Daily",
                            TextValue = "día"
                        },
                        new
                        {
                            TextResourceId = 48,
                            TextIndex = "TypesOccurs_Monthly",
                            TextValue = "mes"
                        },
                        new
                        {
                            TextResourceId = 49,
                            TextIndex = "TypesOccurs_Weekly",
                            TextValue = "semana"
                        },
                        new
                        {
                            TextResourceId = 50,
                            TextIndex = "TypesUnitsDailyFrecuency_Hours",
                            TextValue = "horas"
                        },
                        new
                        {
                            TextResourceId = 51,
                            TextIndex = "TypesUnitsDailyFrecuency_Minutes",
                            TextValue = "minutos"
                        },
                        new
                        {
                            TextResourceId = 52,
                            TextIndex = "TypesUnitsDailyFrecuency_Seconds",
                            TextValue = "segundos"
                        },
                        new
                        {
                            TextResourceId = 53,
                            TextIndex = "wednesday",
                            TextValue = "miercoles"
                        },
                        new
                        {
                            TextResourceId = 54,
                            TextIndex = "EnumConversionError",
                            TextValue = "Error al convertir el valor {0} en {1}"
                        });
                });

            modelBuilder.Entity("Formacion.Data.Models.Resources.TextResourceCulture", b =>
                {
                    b.Property<int>("TextResourceCultureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TextResourceCultureId"), 1L, 1);

                    b.Property<int>("ResourceCultureId")
                        .HasColumnType("int");

                    b.Property<int>("TextResourceId")
                        .HasColumnType("int");

                    b.Property<string>("TextValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TextResourceCultureId");

                    b.HasIndex("ResourceCultureId");

                    b.HasIndex("TextResourceId");

                    b.ToTable("TextResourcesCulture", (string)null);

                    b.HasData(
                        new
                        {
                            TextResourceCultureId = 1,
                            ResourceCultureId = 1,
                            TextResourceId = 1,
                            TextValue = "Config must have a value"
                        },
                        new
                        {
                            TextResourceCultureId = 2,
                            ResourceCultureId = 1,
                            TextResourceId = 2,
                            TextValue = "The current date is invalid"
                        },
                        new
                        {
                            TextResourceCultureId = 3,
                            ResourceCultureId = 1,
                            TextResourceId = 3,
                            TextValue = "Date Time must have a value"
                        },
                        new
                        {
                            TextResourceCultureId = 4,
                            ResourceCultureId = 1,
                            TextResourceId = 4,
                            TextValue = "'End at' must be great than 'Starting at'"
                        },
                        new
                        {
                            TextResourceCultureId = 5,
                            ResourceCultureId = 1,
                            TextResourceId = 5,
                            TextValue = "'End at' must have a value"
                        },
                        new
                        {
                            TextResourceCultureId = 6,
                            ResourceCultureId = 1,
                            TextResourceId = 6,
                            TextValue = "the end date cannot be earlier than the current date"
                        },
                        new
                        {
                            TextResourceCultureId = 7,
                            ResourceCultureId = 1,
                            TextResourceId = 7,
                            TextValue = "End date must be great than start date"
                        },
                        new
                        {
                            TextResourceCultureId = 8,
                            ResourceCultureId = 1,
                            TextResourceId = 8,
                            TextValue = "Weekly configuration: 'Every' must be greater than zero"
                        },
                        new
                        {
                            TextResourceCultureId = 9,
                            ResourceCultureId = 1,
                            TextResourceId = 9,
                            TextValue = "Montly configuration: month(s) must be between 1 and 12"
                        },
                        new
                        {
                            TextResourceCultureId = 10,
                            ResourceCultureId = 1,
                            TextResourceId = 10,
                            TextValue = "Montly configuration: must indicate a day of the month great than zero"
                        },
                        new
                        {
                            TextResourceCultureId = 11,
                            ResourceCultureId = 1,
                            TextResourceId = 11,
                            TextValue = "Montly configuration: must indicate a day of the month less or equal than 31"
                        },
                        new
                        {
                            TextResourceCultureId = 12,
                            ResourceCultureId = 1,
                            TextResourceId = 12,
                            TextValue = "Montly configuration: must indicate a day of the month"
                        },
                        new
                        {
                            TextResourceCultureId = 13,
                            ResourceCultureId = 1,
                            TextResourceId = 13,
                            TextValue = "Montly configuration: must indicate the type every day"
                        },
                        new
                        {
                            TextResourceCultureId = 14,
                            ResourceCultureId = 1,
                            TextResourceId = 14,
                            TextValue = "Montly configuration: must indicate a type of day week"
                        },
                        new
                        {
                            TextResourceCultureId = 15,
                            ResourceCultureId = 1,
                            TextResourceId = 15,
                            TextValue = "Weekly configuration: must select one or more days of the week"
                        },
                        new
                        {
                            TextResourceCultureId = 16,
                            ResourceCultureId = 1,
                            TextResourceId = 16,
                            TextValue = "Scheluder not calculate"
                        },
                        new
                        {
                            TextResourceCultureId = 17,
                            ResourceCultureId = 1,
                            TextResourceId = 17,
                            TextValue = "Not next execution time"
                        },
                        new
                        {
                            TextResourceCultureId = 18,
                            ResourceCultureId = 1,
                            TextResourceId = 18,
                            TextValue = "Number of occurs must be great than zero"
                        },
                        new
                        {
                            TextResourceCultureId = 19,
                            ResourceCultureId = 1,
                            TextResourceId = 19,
                            TextValue = "'Occurs every' must be greater or equal than zero"
                        },
                        new
                        {
                            TextResourceCultureId = 20,
                            ResourceCultureId = 1,
                            TextResourceId = 20,
                            TextValue = "'Once at' must have a value"
                        },
                        new
                        {
                            TextResourceCultureId = 21,
                            ResourceCultureId = 1,
                            TextResourceId = 21,
                            TextValue = "Start Date is invalid"
                        },
                        new
                        {
                            TextResourceCultureId = 22,
                            ResourceCultureId = 1,
                            TextResourceId = 22,
                            TextValue = "'Starting at' must have a value"
                        },
                        new
                        {
                            TextResourceCultureId = 23,
                            ResourceCultureId = 1,
                            TextResourceId = 23,
                            TextValue = "wrong configuration"
                        },
                        new
                        {
                            TextResourceCultureId = 24,
                            ResourceCultureId = 1,
                            TextResourceId = 24,
                            TextValue = "ever {0} {1} between {2} and {3}"
                        },
                        new
                        {
                            TextResourceCultureId = 25,
                            ResourceCultureId = 1,
                            TextResourceId = 25,
                            TextValue = "occurs once at {0}"
                        },
                        new
                        {
                            TextResourceCultureId = 26,
                            ResourceCultureId = 1,
                            TextResourceId = 26,
                            TextValue = "Occurs {0} of very {1} months"
                        },
                        new
                        {
                            TextResourceCultureId = 27,
                            ResourceCultureId = 1,
                            TextResourceId = 27,
                            TextValue = "the {0}"
                        },
                        new
                        {
                            TextResourceCultureId = 28,
                            ResourceCultureId = 1,
                            TextResourceId = 28,
                            TextValue = "the {0} {1}"
                        },
                        new
                        {
                            TextResourceCultureId = 29,
                            ResourceCultureId = 1,
                            TextResourceId = 29,
                            TextValue = "Occurs once. Schedule will be used on {0} at {1} starting on {2}"
                        },
                        new
                        {
                            TextResourceCultureId = 30,
                            ResourceCultureId = 1,
                            TextResourceId = 30,
                            TextValue = "{0} starting on {1}"
                        },
                        new
                        {
                            TextResourceCultureId = 31,
                            ResourceCultureId = 1,
                            TextResourceId = 31,
                            TextValue = "Occurs every {0}{1}{2}. Schedule will be used on {3} at {4}"
                        },
                        new
                        {
                            TextResourceCultureId = 32,
                            ResourceCultureId = 1,
                            TextResourceId = 32,
                            TextValue = " and "
                        },
                        new
                        {
                            TextResourceCultureId = 33,
                            ResourceCultureId = 1,
                            TextResourceId = 33,
                            TextValue = "Occurs every {0} weeks on {1}"
                        },
                        new
                        {
                            TextResourceCultureId = 34,
                            ResourceCultureId = 1,
                            TextResourceId = 34,
                            TextValue = "friday"
                        },
                        new
                        {
                            TextResourceCultureId = 35,
                            ResourceCultureId = 1,
                            TextResourceId = 35,
                            TextValue = "monday"
                        },
                        new
                        {
                            TextResourceCultureId = 36,
                            ResourceCultureId = 1,
                            TextResourceId = 36,
                            TextValue = "saturday"
                        },
                        new
                        {
                            TextResourceCultureId = 37,
                            ResourceCultureId = 1,
                            TextResourceId = 37,
                            TextValue = "sunday"
                        },
                        new
                        {
                            TextResourceCultureId = 38,
                            ResourceCultureId = 1,
                            TextResourceId = 38,
                            TextValue = "thursday"
                        },
                        new
                        {
                            TextResourceCultureId = 39,
                            ResourceCultureId = 1,
                            TextResourceId = 39,
                            TextValue = "tuesday"
                        },
                        new
                        {
                            TextResourceCultureId = 40,
                            ResourceCultureId = 1,
                            TextResourceId = 40,
                            TextValue = "weekday"
                        },
                        new
                        {
                            TextResourceCultureId = 41,
                            ResourceCultureId = 1,
                            TextResourceId = 41,
                            TextValue = "first"
                        },
                        new
                        {
                            TextResourceCultureId = 42,
                            ResourceCultureId = 1,
                            TextResourceId = 42,
                            TextValue = "fourth"
                        },
                        new
                        {
                            TextResourceCultureId = 43,
                            ResourceCultureId = 1,
                            TextResourceId = 43,
                            TextValue = "last"
                        },
                        new
                        {
                            TextResourceCultureId = 44,
                            ResourceCultureId = 1,
                            TextResourceId = 44,
                            TextValue = "second"
                        },
                        new
                        {
                            TextResourceCultureId = 45,
                            ResourceCultureId = 1,
                            TextResourceId = 45,
                            TextValue = "third"
                        },
                        new
                        {
                            TextResourceCultureId = 46,
                            ResourceCultureId = 1,
                            TextResourceId = 46,
                            TextValue = "weekend"
                        },
                        new
                        {
                            TextResourceCultureId = 47,
                            ResourceCultureId = 1,
                            TextResourceId = 47,
                            TextValue = "daily"
                        },
                        new
                        {
                            TextResourceCultureId = 48,
                            ResourceCultureId = 1,
                            TextResourceId = 48,
                            TextValue = "monthly"
                        },
                        new
                        {
                            TextResourceCultureId = 49,
                            ResourceCultureId = 1,
                            TextResourceId = 49,
                            TextValue = "weekly"
                        },
                        new
                        {
                            TextResourceCultureId = 50,
                            ResourceCultureId = 1,
                            TextResourceId = 50,
                            TextValue = "hours"
                        },
                        new
                        {
                            TextResourceCultureId = 51,
                            ResourceCultureId = 1,
                            TextResourceId = 51,
                            TextValue = "minutes"
                        },
                        new
                        {
                            TextResourceCultureId = 52,
                            ResourceCultureId = 1,
                            TextResourceId = 52,
                            TextValue = "seconds"
                        },
                        new
                        {
                            TextResourceCultureId = 53,
                            ResourceCultureId = 1,
                            TextResourceId = 53,
                            TextValue = "wednesday"
                        },
                        new
                        {
                            TextResourceCultureId = 54,
                            ResourceCultureId = 1,
                            TextResourceId = 54,
                            TextValue = "Error to convert {0} at {1}"
                        },
                        new
                        {
                            TextResourceCultureId = 55,
                            ResourceCultureId = 2,
                            TextResourceId = 1,
                            TextValue = "Config must have a value"
                        },
                        new
                        {
                            TextResourceCultureId = 56,
                            ResourceCultureId = 2,
                            TextResourceId = 2,
                            TextValue = "The current date is invalid"
                        },
                        new
                        {
                            TextResourceCultureId = 57,
                            ResourceCultureId = 2,
                            TextResourceId = 3,
                            TextValue = "Date Time must have a value"
                        },
                        new
                        {
                            TextResourceCultureId = 58,
                            ResourceCultureId = 2,
                            TextResourceId = 4,
                            TextValue = "'End at' must be great than 'Starting at'"
                        },
                        new
                        {
                            TextResourceCultureId = 59,
                            ResourceCultureId = 2,
                            TextResourceId = 5,
                            TextValue = "'End at' must have a value"
                        },
                        new
                        {
                            TextResourceCultureId = 60,
                            ResourceCultureId = 2,
                            TextResourceId = 6,
                            TextValue = "the end date cannot be earlier than the current date"
                        },
                        new
                        {
                            TextResourceCultureId = 61,
                            ResourceCultureId = 2,
                            TextResourceId = 7,
                            TextValue = "End date must be great than start date"
                        },
                        new
                        {
                            TextResourceCultureId = 62,
                            ResourceCultureId = 2,
                            TextResourceId = 8,
                            TextValue = "Weekly configuration: 'Every' must be greater than zero"
                        },
                        new
                        {
                            TextResourceCultureId = 63,
                            ResourceCultureId = 2,
                            TextResourceId = 9,
                            TextValue = "Montly configuration: month(s) must be between 1 and 12"
                        },
                        new
                        {
                            TextResourceCultureId = 64,
                            ResourceCultureId = 2,
                            TextResourceId = 10,
                            TextValue = "Montly configuration: must indicate a day of the month great than zero"
                        },
                        new
                        {
                            TextResourceCultureId = 65,
                            ResourceCultureId = 2,
                            TextResourceId = 11,
                            TextValue = "Montly configuration: must indicate a day of the month less or equal than 31"
                        },
                        new
                        {
                            TextResourceCultureId = 66,
                            ResourceCultureId = 2,
                            TextResourceId = 12,
                            TextValue = "Montly configuration: must indicate a day of the month"
                        },
                        new
                        {
                            TextResourceCultureId = 67,
                            ResourceCultureId = 2,
                            TextResourceId = 13,
                            TextValue = "Montly configuration: must indicate the type every day"
                        },
                        new
                        {
                            TextResourceCultureId = 68,
                            ResourceCultureId = 2,
                            TextResourceId = 14,
                            TextValue = "Montly configuration: must indicate a type of day week"
                        },
                        new
                        {
                            TextResourceCultureId = 69,
                            ResourceCultureId = 2,
                            TextResourceId = 15,
                            TextValue = "Weekly configuration: must select one or more days of the week"
                        },
                        new
                        {
                            TextResourceCultureId = 70,
                            ResourceCultureId = 2,
                            TextResourceId = 16,
                            TextValue = "Scheluder not calculate"
                        },
                        new
                        {
                            TextResourceCultureId = 71,
                            ResourceCultureId = 2,
                            TextResourceId = 17,
                            TextValue = "Not next execution time"
                        },
                        new
                        {
                            TextResourceCultureId = 72,
                            ResourceCultureId = 2,
                            TextResourceId = 18,
                            TextValue = "Number of occurs must be great than zero"
                        },
                        new
                        {
                            TextResourceCultureId = 73,
                            ResourceCultureId = 2,
                            TextResourceId = 19,
                            TextValue = "'Occurs every' must be greater or equal than zero"
                        },
                        new
                        {
                            TextResourceCultureId = 74,
                            ResourceCultureId = 2,
                            TextResourceId = 20,
                            TextValue = "'Once at' must have a value"
                        },
                        new
                        {
                            TextResourceCultureId = 75,
                            ResourceCultureId = 2,
                            TextResourceId = 21,
                            TextValue = "Start Date is invalid"
                        },
                        new
                        {
                            TextResourceCultureId = 76,
                            ResourceCultureId = 2,
                            TextResourceId = 22,
                            TextValue = "'Starting at' must have a value"
                        },
                        new
                        {
                            TextResourceCultureId = 77,
                            ResourceCultureId = 2,
                            TextResourceId = 23,
                            TextValue = "wrong configuration"
                        },
                        new
                        {
                            TextResourceCultureId = 78,
                            ResourceCultureId = 2,
                            TextResourceId = 24,
                            TextValue = "ever {0} {1} between {2} and {3}"
                        },
                        new
                        {
                            TextResourceCultureId = 79,
                            ResourceCultureId = 2,
                            TextResourceId = 25,
                            TextValue = "occurs once at {0}"
                        },
                        new
                        {
                            TextResourceCultureId = 80,
                            ResourceCultureId = 2,
                            TextResourceId = 26,
                            TextValue = "Occurs {0} of very {1} months"
                        },
                        new
                        {
                            TextResourceCultureId = 81,
                            ResourceCultureId = 2,
                            TextResourceId = 27,
                            TextValue = "the {0}"
                        },
                        new
                        {
                            TextResourceCultureId = 82,
                            ResourceCultureId = 2,
                            TextResourceId = 28,
                            TextValue = "the {0} {1}"
                        },
                        new
                        {
                            TextResourceCultureId = 83,
                            ResourceCultureId = 2,
                            TextResourceId = 29,
                            TextValue = "Occurs once. Schedule will be used on {0} at {1} starting on {2}"
                        },
                        new
                        {
                            TextResourceCultureId = 84,
                            ResourceCultureId = 2,
                            TextResourceId = 30,
                            TextValue = "{0} starting on {1}"
                        },
                        new
                        {
                            TextResourceCultureId = 85,
                            ResourceCultureId = 2,
                            TextResourceId = 31,
                            TextValue = "Occurs every {0}{1}{2}. Schedule will be used on {3} at {4}"
                        },
                        new
                        {
                            TextResourceCultureId = 86,
                            ResourceCultureId = 2,
                            TextResourceId = 32,
                            TextValue = " and "
                        },
                        new
                        {
                            TextResourceCultureId = 87,
                            ResourceCultureId = 2,
                            TextResourceId = 33,
                            TextValue = "Occurs every {0} weeks on {1}"
                        },
                        new
                        {
                            TextResourceCultureId = 88,
                            ResourceCultureId = 2,
                            TextResourceId = 34,
                            TextValue = "friday"
                        },
                        new
                        {
                            TextResourceCultureId = 89,
                            ResourceCultureId = 2,
                            TextResourceId = 35,
                            TextValue = "monday"
                        },
                        new
                        {
                            TextResourceCultureId = 90,
                            ResourceCultureId = 2,
                            TextResourceId = 36,
                            TextValue = "saturday"
                        },
                        new
                        {
                            TextResourceCultureId = 91,
                            ResourceCultureId = 2,
                            TextResourceId = 37,
                            TextValue = "sunday"
                        },
                        new
                        {
                            TextResourceCultureId = 92,
                            ResourceCultureId = 2,
                            TextResourceId = 38,
                            TextValue = "thursday"
                        },
                        new
                        {
                            TextResourceCultureId = 93,
                            ResourceCultureId = 2,
                            TextResourceId = 39,
                            TextValue = "tuesday"
                        },
                        new
                        {
                            TextResourceCultureId = 94,
                            ResourceCultureId = 2,
                            TextResourceId = 40,
                            TextValue = "weekday"
                        },
                        new
                        {
                            TextResourceCultureId = 95,
                            ResourceCultureId = 2,
                            TextResourceId = 41,
                            TextValue = "first"
                        },
                        new
                        {
                            TextResourceCultureId = 96,
                            ResourceCultureId = 2,
                            TextResourceId = 42,
                            TextValue = "fourth"
                        },
                        new
                        {
                            TextResourceCultureId = 97,
                            ResourceCultureId = 2,
                            TextResourceId = 43,
                            TextValue = "last"
                        },
                        new
                        {
                            TextResourceCultureId = 98,
                            ResourceCultureId = 2,
                            TextResourceId = 44,
                            TextValue = "second"
                        },
                        new
                        {
                            TextResourceCultureId = 99,
                            ResourceCultureId = 2,
                            TextResourceId = 45,
                            TextValue = "third"
                        },
                        new
                        {
                            TextResourceCultureId = 100,
                            ResourceCultureId = 2,
                            TextResourceId = 46,
                            TextValue = "weekend"
                        },
                        new
                        {
                            TextResourceCultureId = 101,
                            ResourceCultureId = 2,
                            TextResourceId = 47,
                            TextValue = "daily"
                        },
                        new
                        {
                            TextResourceCultureId = 102,
                            ResourceCultureId = 2,
                            TextResourceId = 48,
                            TextValue = "monthly"
                        },
                        new
                        {
                            TextResourceCultureId = 103,
                            ResourceCultureId = 2,
                            TextResourceId = 49,
                            TextValue = "weekly"
                        },
                        new
                        {
                            TextResourceCultureId = 104,
                            ResourceCultureId = 2,
                            TextResourceId = 50,
                            TextValue = "hours"
                        },
                        new
                        {
                            TextResourceCultureId = 105,
                            ResourceCultureId = 2,
                            TextResourceId = 51,
                            TextValue = "minutes"
                        },
                        new
                        {
                            TextResourceCultureId = 106,
                            ResourceCultureId = 2,
                            TextResourceId = 52,
                            TextValue = "seconds"
                        },
                        new
                        {
                            TextResourceCultureId = 107,
                            ResourceCultureId = 2,
                            TextResourceId = 53,
                            TextValue = "wednesday"
                        },
                        new
                        {
                            TextResourceCultureId = 108,
                            ResourceCultureId = 2,
                            TextResourceId = 54,
                            TextValue = "Error to convert {0} at {1}"
                        });
                });

            modelBuilder.Entity("Formacion.Data.Models.Resources.TextResourceCulture", b =>
                {
                    b.HasOne("Formacion.Data.Models.Resources.ResourceCulture", "Culture")
                        .WithMany()
                        .HasForeignKey("ResourceCultureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Formacion.Data.Models.Resources.TextResource", "Resource")
                        .WithMany()
                        .HasForeignKey("TextResourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Culture");

                    b.Navigation("Resource");
                });
#pragma warning restore 612, 618
        }
    }
}
