//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formacion.Validators {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Formacion.Validators.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración debe tener un valor.
        /// </summary>
        public static string ConfigMustHasValue {
            get {
                return ResourceManager.GetString("ConfigMustHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha actual es incorrecta.
        /// </summary>
        public static string CurrentDateInvalid {
            get {
                return ResourceManager.GetString("CurrentDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha debe tener un valor.
        /// </summary>
        public static string DateTimeMustHasValue {
            get {
                return ResourceManager.GetString("DateTimeMustHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;Finaliza en&apos; debe ser mas grande que &apos;Comienza en&apos;.
        /// </summary>
        public static string EndAtMinorStartingAt {
            get {
                return ResourceManager.GetString("EndAtMinorStartingAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;Finaliza en&apos; debe tener un valor.
        /// </summary>
        public static string EndAtNotHasValue {
            get {
                return ResourceManager.GetString("EndAtNotHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha final no puede ser menor que la fecha actual.
        /// </summary>
        public static string EndDateAerlierCurrentDate {
            get {
                return ResourceManager.GetString("EndDateAerlierCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de finalización debe ser mayor que la fecha de comienzo.
        /// </summary>
        public static string EndDateGreatStartDate {
            get {
                return ResourceManager.GetString("EndDateGreatStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración semanal: &apos;Cada&apos; debe ser mayor que zero.
        /// </summary>
        public static string EveryMustGreatZero {
            get {
                return ResourceManager.GetString("EveryMustGreatZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion mensual: mes(s) debe estar entre 1 y 12.
        /// </summary>
        public static string MonthBeBetween1And12 {
            get {
                return ResourceManager.GetString("MonthBeBetween1And12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion mensual: debe indicar un día del mes mayor que cero.
        /// </summary>
        public static string MustIndicateDayGreatZero {
            get {
                return ResourceManager.GetString("MustIndicateDayGreatZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion mensual: debe indicar un día del mes menor o igual que 31.
        /// </summary>
        public static string MustIndicateDayLes31 {
            get {
                return ResourceManager.GetString("MustIndicateDayLes31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion mensual: debe indicar un día del mes.
        /// </summary>
        public static string MustIndicateDayOfMonth {
            get {
                return ResourceManager.GetString("MustIndicateDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion mensual: debe indicar el tipo de cada día.
        /// </summary>
        public static string MustIndicateTypeEveryDay {
            get {
                return ResourceManager.GetString("MustIndicateTypeEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion mensual: debe indicar el tipo de día de la semana.
        /// </summary>
        public static string MustIndicateTypeOfDayWeek {
            get {
                return ResourceManager.GetString("MustIndicateTypeOfDayWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración semanal: debe seleccionar un o mas días de la semana.
        /// </summary>
        public static string MustSelectDayWeek {
            get {
                return ResourceManager.GetString("MustSelectDayWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay calculo.
        /// </summary>
        public static string NotCalculate {
            get {
                return ResourceManager.GetString("NotCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay proxima ejecución.
        /// </summary>
        public static string NotNextExecution {
            get {
                return ResourceManager.GetString("NotNextExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de repeticiones debe ser mayor que cero.
        /// </summary>
        public static string NumberMustGreaZero {
            get {
                return ResourceManager.GetString("NumberMustGreaZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;Ocurre cada&apos; debe ser mayo o igual que cero.
        /// </summary>
        public static string OccursGreatZero {
            get {
                return ResourceManager.GetString("OccursGreatZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;Ocuerre en&apos; debe tener un valor.
        /// </summary>
        public static string OnceAtValue {
            get {
                return ResourceManager.GetString("OnceAtValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de comienzo incorrecta.
        /// </summary>
        public static string StartDateInvalid {
            get {
                return ResourceManager.GetString("StartDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;Comienza en&apos; debe tener un valor.
        /// </summary>
        public static string StartingAtNotHasValue {
            get {
                return ResourceManager.GetString("StartingAtNotHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración incorrecta.
        /// </summary>
        public static string WrongConfiguration {
            get {
                return ResourceManager.GetString("WrongConfiguration", resourceCulture);
            }
        }
    }
}
