//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formacion.Formatters {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts___Copia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts___Copia() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Formacion.Formatters.Texts.- Copia", typeof(Texts___Copia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cada {0}{1} entre {2} y {3}.
        /// </summary>
        public static string FormatterDailyFrecuency_TextEvery {
            get {
                return ResourceManager.GetString("FormatterDailyFrecuency.TextEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurre una vez en {0}.
        /// </summary>
        public static string FormatterDailyFrecuency_TextOnce {
            get {
                return ResourceManager.GetString("FormatterDailyFrecuency.TextOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurre {0}  cada {1} mes.
        /// </summary>
        public static string FormatterMonthly_TextBase {
            get {
                return ResourceManager.GetString("FormatterMonthly.TextBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a el {0}.
        /// </summary>
        public static string FormatterMonthly_TextTypeDay {
            get {
                return ResourceManager.GetString("FormatterMonthly.TextTypeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a el {0} {1}.
        /// </summary>
        public static string FormatterMonthly_TextTypeEvery {
            get {
                return ResourceManager.GetString("FormatterMonthly.TextTypeEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurre una vez. El horario se utilizará el {0} a las {1} comenzando el {2}.
        /// </summary>
        public static string FormatterOnce_TextBase {
            get {
                return ResourceManager.GetString("FormatterOnce.TextBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} comenzando el {1}.
        /// </summary>
        public static string FormatterRecurring_TextBase {
            get {
                return ResourceManager.GetString("FormatterRecurring.TextBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurre cada {0}. El horario se utilizará el {1} a las {2}.
        /// </summary>
        public static string FormatterRecurring_TextNoConfigWeekly {
            get {
                return ResourceManager.GetString("FormatterRecurring.TextNoConfigWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a y.
        /// </summary>
        public static string FormatterWeekly_TextAnd {
            get {
                return ResourceManager.GetString("FormatterWeekly.TextAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurre cada {0} semanas en {1}.
        /// </summary>
        public static string FormatterWeekly_TextBase {
            get {
                return ResourceManager.GetString("FormatterWeekly.TextBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a viernes.
        /// </summary>
        public static string friday {
            get {
                return ResourceManager.GetString("friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lunes.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sabado.
        /// </summary>
        public static string saturday {
            get {
                return ResourceManager.GetString("saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a domingo.
        /// </summary>
        public static string sunday {
            get {
                return ResourceManager.GetString("sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a jueves.
        /// </summary>
        public static string thursday {
            get {
                return ResourceManager.GetString("thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a martes.
        /// </summary>
        public static string tuesday {
            get {
                return ResourceManager.GetString("tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a miercoles.
        /// </summary>
        public static string wednesday {
            get {
                return ResourceManager.GetString("wednesday", resourceCulture);
            }
        }
    }
}
